import { Program, NewsItem } from '@/app/types/program';

export const mockPrograms: Program[] = [
  {
    id: '1',
    title: 'Biomedical Engineering Research Program',
    country: 'USA',
    institution: 'Stanford University',
    field: 'bioengineering',
    description: 'Intensive summer research program focusing on tissue engineering and regenerative medicine. Work alongside leading researchers on cutting-edge projects.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-03-15'),
    programStart: new Date('2026-06-20'),
    duration: '8 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 15,
    requirements: ['GPA 3.5+', 'Biology/Chemistry coursework', 'Letter of recommendation', 'Essay'],
    benefits: ['$3,000 stipend', 'Housing included', 'Lab certification', 'Networking events'],
  },
  {
    id: '2',
    title: 'AI & Machine Learning Bootcamp',
    country: 'UK',
    institution: 'University of Cambridge',
    field: 'computer-science',
    description: 'Comprehensive program covering deep learning, neural networks, and practical AI applications. Build real-world projects with industry mentors.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 18, max: 25 },
    applicationDeadline: new Date('2026-02-28'),
    programStart: new Date('2026-07-01'),
    duration: '6 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 25,
    requirements: ['Programming experience', 'Math proficiency', 'Portfolio', 'Statement of purpose'],
    benefits: ['Certificate', 'Industry connections', 'Project showcase', 'Career guidance'],
  },
  {
    id: '3',
    title: 'Global Business Leadership Summit',
    country: 'Singapore',
    institution: 'National University of Singapore',
    field: 'business',
    description: 'Immersive business program exploring Asian markets, entrepreneurship, and global trade dynamics. Includes company visits and networking.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 23 },
    applicationDeadline: new Date('2026-04-01'),
    programStart: new Date('2026-08-10'),
    duration: '4 weeks',
    applicationCost: 50,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 35,
    requirements: ['Interest in business', 'English proficiency', 'Essay', 'Resume'],
    benefits: ['Company visits', 'Networking dinner', 'Certificate', 'Mentorship'],
  },
  {
    id: '4',
    title: 'Digital Arts & Design Intensive',
    country: 'Germany',
    institution: 'Berlin University of the Arts',
    field: 'arts',
    description: 'Creative program exploring digital media, UX/UI design, and interactive installations. Culminates in a public exhibition of student work.',
    format: 'offline',
    residence: 'homestay',
    ageRange: { min: 16, max: 21 },
    applicationDeadline: new Date('2026-03-20'),
    programStart: new Date('2026-07-15'),
    duration: '5 weeks',
    applicationCost: 60,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 40,
    requirements: ['Portfolio submission', 'Artist statement', 'Letter of recommendation'],
    benefits: ['Exhibition opportunity', 'Studio space', 'Materials provided', 'Berlin culture pass'],
  },
  {
    id: '5',
    title: 'Medical Sciences Research Internship',
    country: 'Canada',
    institution: 'University of Toronto',
    field: 'medicine',
    description: 'Hospital-based research program focusing on clinical studies, patient care innovations, and medical technology. Shadow physicians and conduct research.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-15'),
    programStart: new Date('2026-06-01'),
    duration: '10 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 20,
    requirements: ['Pre-med coursework', 'GPA 3.7+', '2 Letters of recommendation', 'Personal statement'],
    benefits: ['Clinical exposure', 'Research publication opportunity', 'Stipend', 'Housing'],
  },
  {
    id: '6',
    title: 'Sustainable Engineering Workshop',
    country: 'Netherlands',
    institution: 'Delft University of Technology',
    field: 'engineering',
    description: 'Hands-on engineering program focused on renewable energy, sustainable design, and green technologies. Work on real-world sustainability challenges.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-03-30'),
    programStart: new Date('2026-07-20'),
    duration: '6 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 30,
    requirements: ['STEM background', 'Essay on sustainability', 'Academic transcript'],
    benefits: ['Lab access', 'Industry partnerships', 'Certificate', 'Bike rental included'],
  },
  {
    id: '8',
    title: 'Global Development & Policy',
    country: 'Switzerland',
    institution: 'Graduate Institute Geneva',
    field: 'social-sciences',
    description: 'Explore international relations, development economics, and policy-making. Visit UN agencies and engage with global leaders.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 23 },
    applicationDeadline: new Date('2026-03-10'),
    programStart: new Date('2026-07-05'),
    duration: '4 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 28,
    requirements: ['Social sciences interest', 'Essay', 'Academic transcript', 'Language proficiency'],
    benefits: ['UN visits', 'Networking events', 'Certificate', 'Travel stipend'],
  },
  {
    id: '10',
    title: 'Philosophy & Ethics Summer School',
    country: 'France',
    institution: 'Sorbonne University',
    field: 'humanities',
    description: 'Intensive philosophy program exploring ethics, political philosophy, and existentialism. Seminars with renowned philosophers and cultural excursions.',
    format: 'offline',
    residence: 'homestay',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-03-25'),
    programStart: new Date('2026-07-10'),
    duration: '5 weeks',
    applicationCost: 55,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 38,
    requirements: ['Essay on philosophical topic', 'Reading list completion', 'Academic transcript'],
    benefits: ['Museum passes', 'Cultural excursions', 'Certificate', 'Book allowance'],
  },
  {
    id: '11',
    title: 'Robotics & Automation Lab',
    country: 'Japan',
    institution: 'Tokyo Institute of Technology',
    field: 'engineering',
    description: 'Cutting-edge robotics program covering AI integration, mechatronics, and autonomous systems. Build and program your own robot.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-28'),
    programStart: new Date('2026-06-25'),
    duration: '6 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 22,
    requirements: ['Engineering/CS background', 'Portfolio', 'Technical essay', '2 recommendations'],
    benefits: ['Robot kit', 'Lab access', 'Competition entry', 'Industry connections'],
  },
  {
    id: '13',
    title: 'Climate Science & Sustainability Lab',
    country: 'Germany',
    institution: 'Technical University of Munich',
    field: 'natural-sciences',
    description: 'Research-intensive program studying climate change, environmental modeling, and sustainability solutions. Collaborate with leading climate scientists.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-05'),
    programStart: new Date('2026-07-08'),
    duration: '9 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 24,
    requirements: ['Environmental science background', 'Research proposal', 'GPA 3.6+', 'Letter of recommendation'],
    benefits: ['Research stipend', 'Conference attendance', 'Lab certification', 'Housing included'],
  },
  {
    id: '14',
    title: 'Entrepreneurship & Startup Incubator',
    country: 'USA',
    institution: 'MIT',
    field: 'business',
    description: 'Transform your business idea into a viable startup. Access to mentors, investors, and MIT resources. Pitch competition with seed funding prizes.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 25 },
    applicationDeadline: new Date('2026-02-10'),
    programStart: new Date('2026-06-10'),
    duration: '12 weeks',
    applicationCost: 120,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 18,
    requirements: ['Business plan', 'Video pitch', 'Resume', 'Two recommendations'],
    benefits: ['$10,000 potential seed funding', 'Investor network', 'Office space', 'Legal support'],
  },
  {
    id: '15',
    title: 'Cybersecurity & Ethical Hacking',
    country: 'UK',
    institution: 'University of Oxford',
    field: 'computer-science',
    description: 'Advanced cybersecurity program covering penetration testing, cryptography, and network security. Hands-on labs with real-world scenarios.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-03-15'),
    programStart: new Date('2026-07-01'),
    duration: '6 weeks',
    applicationCost: 110,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 20,
    requirements: ['Programming skills', 'Networking knowledge', 'Technical assessment', 'Essay'],
    benefits: ['Industry certification', 'Lab access', 'Career placement support', 'Networking events'],
  },
  {
    id: '17',
    title: 'Neuroscience Research Experience',
    country: 'USA',
    institution: 'Harvard University',
    field: 'medicine',
    description: 'Cutting-edge neuroscience research program focusing on brain imaging, cognitive neuroscience, and neural disorders. Work in world-class labs.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-05'),
    programStart: new Date('2026-06-15'),
    duration: '10 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 12,
    requirements: ['Neuroscience/Biology coursework', 'GPA 3.8+', 'Research experience', 'Two recommendations'],
    benefits: ['$4,000 stipend', 'Publication opportunity', 'Lab techniques certification', 'Housing'],
  },
  {
    id: '18',
    title: 'International Law & Human Rights',
    country: 'Netherlands',
    institution: 'Leiden University',
    field: 'social-sciences',
    description: 'Explore international law, human rights frameworks, and global justice systems. Mock trials and visits to international courts.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-03-18'),
    programStart: new Date('2026-07-12'),
    duration: '4 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 30,
    requirements: ['Interest in law/politics', 'Essay', 'Academic transcript', 'English proficiency'],
    benefits: ['Court visits', 'Certificate', 'Networking dinner', 'Legal writing workshop'],
  },
  {
    id: '19',
    title: 'Quantum Computing Fundamentals',
    country: 'Canada',
    institution: 'University of Waterloo',
    field: 'computer-science',
    description: 'Introduction to quantum computing, quantum algorithms, and quantum information theory. Access to quantum computers and simulators.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-25'),
    programStart: new Date('2026-06-30'),
    duration: '7 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 26,
    requirements: ['Advanced math', 'Physics knowledge', 'Programming skills', 'Technical essay'],
    benefits: ['Quantum lab access', 'Certificate', 'Research project', 'Industry connections'],
  },
  {
    id: '20',
    title: 'Psychology & Behavioral Science',
    country: 'Switzerland',
    institution: 'University of Zurich',
    field: 'social-sciences',
    description: 'Explore cognitive psychology, behavioral economics, and research methods. Conduct experiments and analyze human behavior patterns.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-03-28'),
    programStart: new Date('2026-07-20'),
    duration: '5 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 34,
    requirements: ['Psychology coursework', 'Research interest statement', 'Academic transcript'],
    benefits: ['Lab experience', 'Certificate', 'Research methods training', 'Conference attendance'],
  },
  {
    id: '21',
    title: 'Renewable Energy Engineering',
    country: 'Singapore',
    institution: 'Nanyang Technological University',
    field: 'engineering',
    description: 'Focus on solar, wind, and battery technologies. Design and build renewable energy systems with industry-standard tools.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-03-01'),
    programStart: new Date('2026-07-05'),
    duration: '8 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 28,
    requirements: ['Engineering/Physics background', 'Technical portfolio', 'Essay on sustainability'],
    benefits: ['Industry site visits', 'Certification', 'Project showcase', 'Networking'],
  },
  {
    id: '22',
    title: 'Archaeology Field School',
    country: 'France',
    institution: 'University of Paris',
    field: 'humanities',
    description: 'Hands-on archaeological excavation experience. Learn field techniques, artifact analysis, and historical research at active dig sites.',
    format: 'offline',
    residence: 'homestay',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-04-05'),
    programStart: new Date('2026-07-25'),
    duration: '6 weeks',
    applicationCost: 60,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 40,
    requirements: ['History/Anthropology interest', 'Physical fitness', 'Statement of purpose'],
    benefits: ['Field experience', 'Museum visits', 'Certificate', 'Research credit'],
  },
  {
    id: '23',
    title: 'Game Development & Design',
    country: 'Japan',
    institution: 'DigiPen Institute Tokyo',
    field: 'computer-science',
    description: 'Create your own video game from concept to playable prototype. Learn Unity, game design principles, and industry workflows.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 16, max: 22 },
    applicationDeadline: new Date('2026-04-12'),
    programStart: new Date('2026-08-01'),
    duration: '6 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 35,
    requirements: ['Basic programming', 'Game design document', 'Portfolio', 'Creative essay'],
    benefits: ['Published game', 'Industry mentorship', 'Software licenses', 'Demo day presentation'],
  },
  {
    id: '24',
    title: 'Public Health & Epidemiology',
    country: 'UK',
    institution: 'London School of Hygiene',
    field: 'medicine',
    description: 'Study disease prevention, health policy, and epidemiological methods. Analyze real public health challenges and propose solutions.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-08'),
    programStart: new Date('2026-06-20'),
    duration: '7 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 32,
    requirements: ['Biology/Statistics background', 'Statement of purpose', 'Academic transcript'],
    benefits: ['Certificate', 'WHO collaboration project', 'Field visits', 'Career guidance'],
  },
  {
    id: '25',
    title: 'Mathematical Modeling & Simulation',
    country: 'Germany',
    institution: 'University of Heidelberg',
    field: 'natural-sciences',
    description: 'Apply advanced mathematics to real-world problems in physics, biology, and economics. Develop computational models and simulations.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-25'),
    programStart: new Date('2026-06-28'),
    duration: '8 weeks',
    applicationCost: 65,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 27,
    requirements: ['Advanced math', 'Programming experience', 'Research proposal', 'Recommendation'],
    benefits: ['Research publication', 'Supercomputer access', 'Conference presentation', 'Housing'],
  },
  {
    id: '26',
    title: 'Fashion Design & Textile Innovation',
    country: 'France',
    institution: 'École de la Chambre Syndicale',
    field: 'arts',
    description: 'Learn haute couture techniques, sustainable fashion, and textile technology. Create your own collection for a runway show.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-04-15'),
    programStart: new Date('2026-07-18'),
    duration: '5 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 38,
    requirements: ['Design portfolio', 'Creative statement', 'Sewing experience preferred'],
    benefits: ['Runway show', 'Fashion week tickets', 'Industry connections', 'Materials provided'],
  },
  {
    id: '27',
    title: 'Aerospace Engineering Workshop',
    country: 'USA',
    institution: 'Caltech',
    field: 'engineering',
    description: 'Design, build, and test aerospace systems. Topics include aerodynamics, propulsion, and spacecraft design with JPL facility access.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-18'),
    programStart: new Date('2026-06-22'),
    duration: '9 weeks',
    applicationCost: 110,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 16,
    requirements: ['Physics/Math strong background', 'GPA 3.7+', 'Technical essay', 'Two recommendations'],
    benefits: ['JPL tour', 'NASA connections', 'Flight test', 'Research certificate'],
  },
  {
    id: '28',
    title: 'Financial Markets & Trading',
    country: 'Singapore',
    institution: 'Singapore Management University',
    field: 'business',
    description: 'Learn investment strategies, risk management, and financial analysis. Access to trading simulators and market data platforms.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-03-12'),
    programStart: new Date('2026-07-22'),
    duration: '5 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 30,
    requirements: ['Economics/Math background', 'Essay', 'Resume', 'Academic transcript'],
    benefits: ['Trading certification', 'Bloomberg terminal access', 'Industry mentors', 'Networking events'],
  },
  {
    id: '29',
    title: 'Genetics & Genomics Research',
    country: 'Canada',
    institution: 'McGill University',
    field: 'bioengineering',
    description: 'Explore gene editing, genomic sequencing, and precision medicine. Work with CRISPR technology and modern genetic analysis tools.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-02-22'),
    programStart: new Date('2026-06-18'),
    duration: '10 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 19,
    requirements: ['Molecular biology background', 'GPA 3.6+', 'Research statement', 'Two recommendations'],
    benefits: ['$3,500 stipend', 'Publication opportunity', 'Lab certification', 'Housing'],
  },
  {
    id: '30',
    title: 'Sociology & Urban Studies',
    country: 'Netherlands',
    institution: 'University of Amsterdam',
    field: 'social-sciences',
    description: 'Study urban development, social inequality, and community organization. Conduct fieldwork in Amsterdam neighborhoods.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-03-30'),
    programStart: new Date('2026-07-15'),
    duration: '6 weeks',
    applicationCost: 55,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 36,
    requirements: ['Social sciences interest', 'Research proposal', 'Academic transcript'],
    benefits: ['Field research experience', 'Certificate', 'City tours', 'Research methods training'],
  },
  {
    id: '31',
    title: 'Music Production & Audio Engineering',
    country: 'UK',
    institution: 'Abbey Road Institute',
    field: 'arts',
    description: 'Professional music production program covering recording, mixing, mastering, and sound design. Access to world-class studios.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 24 },
    applicationDeadline: new Date('2026-04-18'),
    programStart: new Date('2026-07-28'),
    duration: '6 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 34,
    requirements: ['Music portfolio', 'Technical aptitude', 'Creative statement'],
    benefits: ['Studio time', 'Industry certification', 'Artist collaborations', 'Demo production'],
  },
  {
    id: '32',
    title: 'Artificial Intelligence Ethics',
    country: 'Switzerland',
    institution: 'ETH Zurich',
    field: 'computer-science',
    description: 'Explore ethical implications of AI, algorithmic bias, and responsible technology development. Interdisciplinary approach combining tech and philosophy.',
    format: 'hybrid',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-20'),
    programStart: new Date('2026-07-10'),
    duration: '5 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 29,
    requirements: ['AI/Ethics background', 'Position paper', 'Academic transcript'],
    benefits: ['Certificate', 'Policy workshop', 'Tech company visits', 'Publication opportunity'],
  },
  {
    id: '34',
    title: 'Political Science & Diplomacy',
    country: 'USA',
    institution: 'Georgetown University',
    field: 'social-sciences',
    description: 'Study international relations, political theory, and diplomatic practice. Participate in Model UN and meet with policymakers.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-28'),
    programStart: new Date('2026-06-25'),
    duration: '6 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 26,
    requirements: ['Political science interest', 'Essay on global issue', 'Academic transcript', 'Recommendation'],
    benefits: ['Capitol Hill visit', 'Embassy tours', 'Model UN participation', 'Certificate'],
  },
  {
    id: '35',
    title: 'Nanotechnology & Materials Science',
    country: 'Japan',
    institution: 'University of Tokyo',
    field: 'engineering',
    description: 'Explore nanoscale engineering, advanced materials, and molecular manipulation. Access to electron microscopes and cleanroom facilities.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-20'),
    programStart: new Date('2026-06-18'),
    duration: '8 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 22,
    requirements: ['Chemistry/Physics background', 'GPA 3.6+', 'Research proposal', 'Two recommendations'],
    benefits: ['Lab certification', 'Research publication', 'Conference attendance', 'Housing'],
  },
  // EXPANDED DATABASE - Additional 50 programs for realism and scale
  {
    id: '37',
    title: 'Sustainable Architecture Workshop',
    country: 'Denmark',
    institution: 'Royal Danish Academy of Fine Arts',
    field: 'arts',
    description: 'Design eco-friendly buildings using sustainable materials and green technologies. Study Copenhagen\'s innovative urban planning.',
    format: 'offline',
    residence: 'homestay',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-05-10'),
    programStart: new Date('2026-09-01'),
    duration: '4 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 33,
    requirements: ['Design portfolio', 'Architecture interest', 'Statement of purpose'],
    benefits: ['Site visits', 'Design software access', 'Certificate', 'Bike included'],
  },
  {
    id: '38',
    title: 'International Journalism & Media Ethics',
    country: 'UK',
    institution: 'BBC Academy London',
    field: 'humanities',
    description: 'Learn investigative journalism, fact-checking, and media ethics. Produce news stories with BBC mentors.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-31'),
    programStart: new Date('2026-07-20'),
    duration: '5 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 29,
    requirements: ['Writing samples', 'Current events knowledge', 'Video interview', 'Essay'],
    benefits: ['BBC press pass', 'Published articles', 'Industry connections', 'Certificate'],
  },

  {
    id: '40',
    title: 'Blockchain & Cryptocurrency Development',
    country: 'Singapore',
    institution: 'Singapore University of Technology',
    field: 'computer-science',
    description: 'Build decentralized applications, smart contracts, and explore blockchain use cases in finance, supply chain, and governance.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 18, max: 25 },
    applicationDeadline: new Date('2026-05-20'),
    programStart: new Date('2026-08-25'),
    duration: '5 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 31,
    requirements: ['Programming skills', 'Cryptography basics', 'Portfolio', 'Technical essay'],
    benefits: ['Industry certification', 'Fintech company visits', 'Hackathon participation', 'Certificate'],
  },
  {
    id: '44',
    title: 'Advanced Robotics & Automation',
    country: 'South Korea',
    institution: 'KAIST',
    field: 'engineering',
    description: 'Design and program humanoid robots, drones, and autonomous vehicles. Access to cutting-edge robotics labs and AI integration.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-28'),
    programStart: new Date('2026-07-12'),
    duration: '8 weeks',
    applicationCost: 110,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 19,
    requirements: ['Engineering/CS degree pursuit', 'Robotics coursework', 'Portfolio', 'Two recommendations'],
    benefits: ['Robot competition', 'Industry partnerships', 'Lab certification', 'Housing'],
  },
  {
    id: '45',
    title: 'Culinary Arts & Food Science',
    country: 'Italy',
    institution: 'ALMA - International School of Italian Cuisine',
    field: 'arts',
    description: 'Learn Italian cooking techniques, food chemistry, and sustainable gastronomy. Work with Michelin-starred chefs.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 18, max: 25 },
    applicationDeadline: new Date('2026-04-30'),
    programStart: new Date('2026-08-18'),
    duration: '4 weeks',
    applicationCost: 120,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 41,
    requirements: ['Culinary interest', 'Basic cooking skills', 'Health certificate', 'Statement of purpose'],
    benefits: ['Professional kitchen access', 'Wine tasting course', 'Certificate', 'Restaurant visits'],
  },
  {
    id: '46',
    title: 'Renewable Energy Policy & Economics',
    country: 'Norway',
    institution: 'University of Oslo',
    field: 'social-sciences',
    description: 'Analyze energy markets, climate policy, and transition to sustainable energy systems. Study Norway\'s renewable energy success.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-04-12'),
    programStart: new Date('2026-07-28'),
    duration: '5 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 35,
    requirements: ['Economics/Environmental studies', 'Policy paper', 'Academic transcript'],
    benefits: ['Hydropower plant visit', 'Government meetings', 'Certificate', 'Research project'],
  },
  {
    id: '47',
    title: 'Digital Marketing & E-Commerce',
    country: 'Netherlands',
    institution: 'Amsterdam School of Marketing',
    field: 'business',
    description: 'Master SEO, social media marketing, analytics, and online business strategies. Create campaigns for real clients.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-05-15'),
    programStart: new Date('2026-08-20'),
    duration: '4 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 43,
    requirements: ['Marketing interest', 'Portfolio/examples', 'Essay'],
    benefits: ['Google Ads certification', 'Agency visits', 'Live campaigns', 'Certificate'],
  },
  {
    id: '50',
    title: 'Materials Science & Nanotechnology',
    country: 'Taiwan',
    institution: 'National Taiwan University',
    field: 'engineering',
    description: 'Develop advanced materials at nanoscale for electronics, energy storage, and biomedical applications. Lab-intensive program.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-04-08'),
    programStart: new Date('2026-07-22'),
    duration: '8 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 24,
    requirements: ['Chemistry/Physics/Engineering', 'GPA 3.5+', 'Research proposal', 'Recommendation'],
    benefits: ['Cleanroom access', 'Research publication', 'Conference attendance', 'Housing'],
  },
  {
    id: '53',
    title: 'Urban Planning & Smart Cities',
    country: 'UAE',
    institution: 'Masdar Institute',
    field: 'engineering',
    description: 'Design sustainable urban infrastructure, smart transportation, and green cities. Study Dubai and Abu Dhabi\'s urban innovations.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-04-25'),
    programStart: new Date('2026-08-10'),
    duration: '5 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 28,
    requirements: ['Engineering/Architecture', 'Urban planning interest', 'Portfolio', 'Essay'],
    benefits: ['City tours', 'Government presentations', 'Certificate', 'Design software access'],
  },
  {
    id: '54',
    title: 'Philosophy of Mind & Cognitive Science',
    country: 'USA',
    institution: 'University of California, Berkeley',
    field: 'humanities',
    description: 'Explore consciousness, artificial intelligence, and the nature of thought. Interdisciplinary approach combining philosophy, neuroscience, and AI.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-22'),
    programStart: new Date('2026-06-28'),
    duration: '6 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 31,
    requirements: ['Philosophy/Psychology coursework', 'Essay on consciousness', 'Academic transcript'],
    benefits: ['Research lab visits', 'Certificate', 'Reading stipend', 'Lecture series access'],
  },
  {
    id: '55',
    title: 'Fintech Innovation & Digital Banking',
    country: 'Hong Kong',
    institution: 'Hong Kong University of Science and Technology',
    field: 'business',
    description: 'Study financial technology, digital payments, and banking innovation. Collaborate with fintech startups and established banks.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 19, max: 25 },
    applicationDeadline: new Date('2026-04-15'),
    programStart: new Date('2026-08-01'),
    duration: '5 weeks',
    applicationCost: 110,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 25,
    requirements: ['Finance/CS background', 'Technical skills', 'Essay', 'Resume'],
    benefits: ['Startup visits', 'Industry certification', 'Hackathon', 'Networking events'],
  },
  {
    id: '56',
    title: 'Glaciology & Climate Change Research',
    country: 'Iceland',
    institution: 'University of Iceland',
    field: 'natural-sciences',
    description: 'Study glaciers, ice cores, and climate patterns. Field work on Vatnajökull glacier with cutting-edge measurement tools.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-03-10'),
    programStart: new Date('2026-07-05'),
    duration: '7 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 29,
    requirements: ['Geology/Environmental science', 'Physical fitness', 'Research proposal', 'Recommendation'],
    benefits: ['Field research', 'Glacier access', 'Research publication', 'Housing'],
  },
  {
    id: '57',
    title: 'Animation & Visual Effects',
    country: 'Canada',
    institution: 'Vancouver Film School',
    field: 'arts',
    description: '3D animation, character design, and VFX production. Create portfolio-quality work using industry-standard software.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 24 },
    applicationDeadline: new Date('2026-05-20'),
    programStart: new Date('2026-09-08'),
    duration: '8 weeks',
    applicationCost: 105,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 38,
    requirements: ['Art portfolio', 'Creative statement', 'Software experience helpful'],
    benefits: ['Software licenses', 'Studio access', 'Industry mentorship', 'Demo reel'],
  },
  {
    id: '58',
    title: 'Medieval History & Manuscript Studies',
    country: 'UK',
    institution: 'University of Oxford',
    field: 'humanities',
    description: 'Study medieval manuscripts, paleography, and European history. Access to Bodleian Library rare book collections.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-04-01'),
    programStart: new Date('2026-07-18'),
    duration: '4 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 33,
    requirements: ['History coursework', 'Latin helpful', 'Research proposal', 'Writing sample'],
    benefits: ['Archive access', 'Museum tours', 'Certificate', 'Research support'],
  },
  {
    id: '59',
    title: 'Semiconductor Physics & Chip Design',
    country: 'Taiwan',
    institution: 'National Tsing Hua University',
    field: 'engineering',
    description: 'Learn semiconductor fabrication, chip architecture, and next-generation computing technologies. Visit TSMC facilities.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-03-18'),
    programStart: new Date('2026-07-08'),
    duration: '9 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 21,
    requirements: ['EE/Physics background', 'GPA 3.6+', 'Technical essay', 'Two recommendations'],
    benefits: ['Fab tour', 'Industry connections', 'Research project', 'Housing'],
  },
  {
    id: '60',
    title: 'Developmental Psychology & Child Studies',
    country: 'Sweden',
    institution: 'Uppsala University',
    field: 'social-sciences',
    description: 'Study child development, educational psychology, and family dynamics. Participate in research studies and observations.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-04-20'),
    programStart: new Date('2026-08-15'),
    duration: '6 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 37,
    requirements: ['Psychology coursework', 'Research interest', 'Statement of purpose', 'Academic transcript'],
    benefits: ['Lab access', 'Daycare observations', 'Certificate', 'Research methods training'],
  },
  {
    id: '61',
    title: 'Volcanology & Geophysical Hazards',
    country: 'Italy',
    institution: 'University of Pisa',
    field: 'natural-sciences',
    description: 'Study active volcanoes, seismic monitoring, and natural disaster preparedness. Field trips to Mt. Etna and Vesuvius.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-04-28'),
    programStart: new Date('2026-08-22'),
    duration: '5 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 30,
    requirements: ['Geology/Earth science', 'Physical fitness', 'Safety training', 'Statement of purpose'],
    benefits: ['Volcano access', 'Monitoring equipment', 'Certificate', 'Field research'],
  },
  {
    id: '63',
    title: 'Organic Chemistry & Drug Synthesis',
    country: 'Switzerland',
    institution: 'ETH Zurich',
    field: 'bioengineering',
    description: 'Advanced organic synthesis techniques for pharmaceutical development. Work on drug discovery projects in modern labs.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-15'),
    programStart: new Date('2026-06-15'),
    duration: '10 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 18,
    requirements: ['Chemistry major', 'GPA 3.7+', 'Lab experience', 'Two recommendations'],
    benefits: ['$3,500 stipend', 'Research publication', 'Lab certification', 'Housing'],
  },
  {
    id: '64',
    title: 'Creative Coding & Generative Art',
    country: 'Netherlands',
    institution: 'Institute of Network Cultures',
    field: 'arts',
    description: 'Use code to create interactive art, generative visuals, and digital installations. Explore p5.js, Processing, and creative AI.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 17, max: 24 },
    applicationDeadline: new Date('2026-05-28'),
    programStart: new Date('2026-09-12'),
    duration: '5 weeks',
    applicationCost: 70,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 44,
    requirements: ['Basic programming', 'Art portfolio', 'Creative statement'],
    benefits: ['Exhibition', 'Software access', 'Certificate', 'Artist network'],
  },
  {
    id: '65',
    title: 'Comparative Literature & Translation Studies',
    country: 'France',
    institution: 'École Normale Supérieure',
    field: 'humanities',
    description: 'Study world literature, literary theory, and translation practice. Workshops with published translators and authors.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-04-10'),
    programStart: new Date('2026-07-25'),
    duration: '6 weeks',
    applicationCost: 65,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 35,
    requirements: ['Language proficiency', 'Translation sample', 'Essay on literature', 'Academic transcript'],
    benefits: ['Literary events', 'Book allowance', 'Certificate', 'Translation workshop'],
  },
  {
    id: '66',
    title: 'Astrobiology & Exoplanet Research',
    country: 'USA',
    institution: 'NASA Ames Research Center',
    field: 'natural-sciences',
    description: 'Search for life beyond Earth through exoplanet analysis, biosignatures, and astrobiology research. Work with NASA scientists.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-02-10'),
    programStart: new Date('2026-06-12'),
    duration: '11 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 14,
    requirements: ['Astronomy/Biology/Chemistry', 'GPA 3.8+', 'Research experience', 'Three recommendations'],
    benefits: ['$4,500 stipend', 'NASA badge', 'Publication opportunity', 'Conference attendance'],
  },
  {
    id: '67',
    title: 'Electronic Music Production & Sound Design',
    country: 'Germany',
    institution: 'dBs Music Berlin',
    field: 'arts',
    description: 'Master Ableton, synthesis, mixing, and mastering. Produce your own electronic music tracks and perform at Berlin clubs.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 24 },
    applicationDeadline: new Date('2026-05-15'),
    programStart: new Date('2026-08-28'),
    duration: '6 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 40,
    requirements: ['Music portfolio', 'DAW experience helpful', 'Creative statement'],
    benefits: ['Studio access', 'Performance opportunity', 'Software licenses', 'Certificate'],
  },

  {
    id: '69',
    title: 'Conflict Resolution & Peace Studies',
    country: 'Norway',
    institution: 'Peace Research Institute Oslo',
    field: 'social-sciences',
    description: 'Study mediation, international conflict, and peacebuilding strategies. Participate in simulated negotiations and workshops.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-04-22'),
    programStart: new Date('2026-08-12'),
    duration: '5 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 33,
    requirements: ['IR/Political science', 'Essay on conflict', 'Academic transcript', 'Recommendation'],
    benefits: ['UN visit', 'Negotiation certificate', 'Networking events', 'Research access'],
  },
  {
    id: '70',
    title: 'Immunology & Vaccine Development',
    country: 'Belgium',
    institution: 'KU Leuven',
    field: 'medicine',
    description: 'Study immune system mechanisms, vaccine design, and infectious disease research. Lab work with immunological assays.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-05'),
    programStart: new Date('2026-07-01'),
    duration: '9 weeks',
    applicationCost: 80,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 23,
    requirements: ['Biology/Immunology', 'GPA 3.6+', 'Lab experience', 'Research proposal'],
    benefits: ['Research stipend', 'Lab techniques', 'Publication opportunity', 'Housing'],
  },
  {
    id: '71',
    title: 'Theater Production & Stage Management',
    country: 'UK',
    institution: 'Royal Academy of Dramatic Art',
    field: 'arts',
    description: 'Learn stage management, lighting design, set construction, and theater production. Work on live performances.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 17, max: 23 },
    applicationDeadline: new Date('2026-05-10'),
    programStart: new Date('2026-09-01'),
    duration: '6 weeks',
    applicationCost: 90,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 34,
    requirements: ['Theater experience', 'Portfolio/resume', 'Creative statement', 'Interview'],
    benefits: ['Show production', 'West End tours', 'Certificate', 'Industry connections'],
  },
  {
    id: '72',
    title: 'Quantum Materials & Superconductivity',
    country: 'Japan',
    institution: 'RIKEN Research Institute',
    field: 'engineering',
    description: 'Explore quantum materials, superconductors, and topological physics. Access to advanced characterization equipment.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-02-28'),
    programStart: new Date('2026-06-25'),
    duration: '10 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 17,
    requirements: ['Physics/Materials science', 'GPA 3.8+', 'Quantum mechanics', 'Research proposal'],
    benefits: ['$4,000 stipend', 'Lab access', 'Publication opportunity', 'Housing'],
  },
  {
    id: '73',
    title: 'Documentary Filmmaking & Storytelling',
    country: 'USA',
    institution: 'Sundance Institute',
    field: 'arts',
    description: 'Create compelling documentaries on social issues. Learn cinematography, interviewing, and editing from award-winning filmmakers.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 18, max: 25 },
    applicationDeadline: new Date('2026-04-15'),
    programStart: new Date('2026-08-05'),
    duration: '5 weeks',
    applicationCost: 110,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 27,
    requirements: ['Film reel/portfolio', 'Director statement', 'Story pitch', 'Recommendation'],
    benefits: ['Film festival submission', 'Equipment access', 'Mentorship', 'Screening event'],
  },
  {
    id: '75',
    title: 'Bioinformatics & Computational Biology',
    country: 'Singapore',
    institution: 'A*STAR Bioinformatics Institute',
    field: 'bioengineering',
    description: 'Apply computational methods to genomics, protein structure prediction, and biological data analysis. Use supercomputers and AI.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-03-22'),
    programStart: new Date('2026-07-15'),
    duration: '8 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 25,
    requirements: ['CS/Biology dual interest', 'Programming skills', 'GPA 3.5+', 'Research statement'],
    benefits: ['Supercomputer access', 'Research publication', 'Certificate', 'Housing'],
  },
  {
    id: '78',
    title: 'Renaissance Art & Art Restoration',
    country: 'Italy',
    institution: 'Accademia di Belle Arti Firenze',
    field: 'arts',
    description: 'Study Renaissance masters and learn art conservation techniques. Restore historical artworks under expert supervision.',
    format: 'offline',
    residence: 'off-campus',
    ageRange: { min: 19, max: 25 },
    applicationDeadline: new Date('2026-05-22'),
    programStart: new Date('2026-09-15'),
    duration: '5 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: false,
    internationalAcceptanceRate: 28,
    requirements: ['Art history background', 'Portfolio', 'Essay on restoration ethics', 'Recommendation'],
    benefits: ['Museum access', 'Restoration workshop', 'Certificate', 'Gallery tours'],
  },
  {
    id: '79',
    title: 'Supply Chain Management & Logistics',
    country: 'Germany',
    institution: 'Technical University of Munich',
    field: 'business',
    description: 'Optimize supply chains, learn inventory management, and study Industry 4.0 logistics. Company visits to BMW and Siemens.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 19, max: 24 },
    applicationDeadline: new Date('2026-04-12'),
    programStart: new Date('2026-07-28'),
    duration: '6 weeks',
    applicationCost: 85,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 34,
    requirements: ['Business/Engineering', 'Analytics interest', 'Essay', 'Resume'],
    benefits: ['Factory tours', 'Industry certification', 'Certificate', 'Networking events'],
  },
  {
    id: '80',
    title: 'Stem Cell Biology & Regenerative Medicine',
    country: 'Japan',
    institution: 'Kyoto University',
    field: 'bioengineering',
    description: 'Research stem cell differentiation, tissue engineering, and regenerative therapies. Nobel Prize-winning lab environment.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-02-18'),
    programStart: new Date('2026-06-20'),
    duration: '11 weeks',
    applicationCost: 100,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 15,
    requirements: ['Molecular biology', 'GPA 3.8+', 'Research experience', 'Three recommendations'],
    benefits: ['$4,200 stipend', 'Publication opportunity', 'Lab certification', 'Housing'],
  },
  {
    id: '82',
    title: 'Aviation Engineering & Aerospace Design',
    country: 'France',
    institution: 'ISAE-SUPAERO Toulouse',
    field: 'engineering',
    description: 'Design aircraft systems, study aerodynamics, and visit Airbus facilities. Hands-on projects with flight simulators.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 23 },
    applicationDeadline: new Date('2026-03-25'),
    programStart: new Date('2026-07-12'),
    duration: '7 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 22,
    requirements: ['Engineering/Physics', 'GPA 3.6+', 'Technical project', 'Two recommendations'],
    benefits: ['Airbus tour', 'Simulator access', 'Certificate', 'Industry connections'],
  },
  {
    id: '83',
    title: 'Gender Studies & Feminist Theory',
    country: 'Sweden',
    institution: 'Lund University',
    field: 'social-sciences',
    description: 'Explore gender equality, feminist philosophy, and social justice movements. Study Sweden\'s gender equality policies.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 18, max: 24 },
    applicationDeadline: new Date('2026-04-28'),
    programStart: new Date('2026-08-20'),
    duration: '5 weeks',
    applicationCost: 65,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 39,
    requirements: ['Gender studies/Sociology', 'Critical essay', 'Academic transcript'],
    benefits: ['Policy seminars', 'NGO visits', 'Certificate', 'Research workshop'],
  },
  {
    id: '84',
    title: 'Mobile App Development & UI/UX Design',
    country: 'USA',
    institution: 'General Assembly San Francisco',
    field: 'computer-science',
    description: 'Build iOS and Android apps with modern frameworks. Learn UI/UX principles and launch your app to app stores.',
    format: 'hybrid',
    residence: 'off-campus',
    ageRange: { min: 17, max: 24 },
    applicationDeadline: new Date('2026-05-25'),
    programStart: new Date('2026-09-10'),
    duration: '6 weeks',
    applicationCost: 95,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 42,
    requirements: ['Programming basics', 'Portfolio/idea', 'Technical assessment'],
    benefits: ['App published', 'Industry mentorship', 'Certificate', 'Hackathon participation'],
  },
  {
    id: '85',
    title: 'Oceanography & Marine Conservation',
    country: 'Portugal',
    institution: 'University of the Azores',
    field: 'natural-sciences',
    description: 'Study ocean currents, marine ecosystems, and whale conservation. Research in the Atlantic Ocean with boat expeditions.',
    format: 'offline',
    residence: 'on-campus',
    ageRange: { min: 17, max: 22 },
    applicationDeadline: new Date('2026-03-30'),
    programStart: new Date('2026-07-22'),
    duration: '8 weeks',
    applicationCost: 75,
    hasLowIncomeDiscount: true,
    internationalAcceptanceRate: 35,
    requirements: ['Marine biology/Oceanography', 'Swimming skills', 'Statement of purpose', 'Recommendation'],
    benefits: ['Boat research', 'Diving optional', 'Certificate', 'Housing'],
  },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'Stanford Biomedical Program - Applications Close in 5 Days',
    description: 'Final deadline: March 15. Complete your essay and recommendation letters now.',
    date: new Date('2026-01-21'),
    type: 'deadline',
    programId: '1',
  },
  {
    id: '2',
    title: 'Updated Requirements for Cambridge AI Bootcamp',
    description: 'New prerequisite added: basic Python knowledge required. Portfolio guidelines updated with code examples.',
    date: new Date('2026-01-20'),
    type: 'announcement',
    programId: '2',
  },
  {
    id: '3',
    title: 'Essay Writing Tip: Avoid Generic Opening Statements',
    description: 'Starting with "Ever since I was young..." or "In today\'s world..." weakens your essay. Open with a specific moment or observation that reveals your unique perspective.',
    date: new Date('2026-01-20'),
    type: 'essay-tip',
  },
  {
    id: '5',
    title: 'New Essay Prompt Added for NUS Business Summit',
    description: 'Supplemental essay question: "Describe a business challenge in your community and your proposed solution." (300 words max)',
    date: new Date('2026-01-19'),
    type: 'announcement',
    programId: '3',
  },
  {
    id: '6',
    title: 'Essay Writing Tip: Show Intellectual Curiosity',
    description: 'Committees look for students who ask questions. Instead of stating what you know, explain what you want to discover and why it matters to you.',
    date: new Date('2026-01-18'),
    type: 'essay-tip',
  },
  {
    id: '7',
    title: 'Robotics Lab Tokyo - Application Fee Waiver Available',
    description: 'Students from developing countries can request fee waiver. Submit request form by February 20.',
    date: new Date('2026-01-18'),
    type: 'announcement',
    programId: '11',
  },
  {
    id: '8',
    title: 'Essay Writing Tip: The "Why This Program?" Formula',
    description: 'Connect specific program features to your goals. Formula: "Because [program offers X], I can [achieve Y], which connects to my goal of [Z]."',
    date: new Date('2026-01-17'),
    type: 'essay-tip',
  },
  {
    id: '9',
    title: 'Deadline Alert: Multiple Programs Close February 28',
    description: '3 programs have the same deadline. Prioritize based on acceptance rates and your readiness. Use our AI essay tool to speed up revisions.',
    date: new Date('2026-01-21'),
    type: 'deadline',
  },
  {
    id: '10',
    title: 'Essay Writing Tip: Word Limit Strategy',
    description: 'At 90% of word limit, stop adding. Use remaining space for precision: replace weak verbs, cut filler words, strengthen your thesis.',
    date: new Date('2026-01-19'),
    type: 'essay-tip',
  },
];